---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
All in the golden afternoon  
Full leisurely we glide;  
For both our oars, with little skill,  
By little arms are plied,  
While little hands make vain pretence  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Out of the night that covers me,  
      Black as the pit from pole to pole,  
I thank whatever gods may be  
      For my unconquerable soul.  
  
In the fell clutch of circumstance  
      I have not winced nor cried aloud.  
Under the bludgeonings of chance  
      My head is bloody, but unbowed.  
  
Beyond this place of wrath and tears  
      Looms but the Horror of the shade,  
And yet the menace of the years  
      Finds and shall find me unafraid.  
  
It matters not how strait the gate,  
      How charged with punishments the scroll,  
I am the master of my fate,  
      I am the captain of my soul.  
        